### ISSUE TITLE
List all ec2 instances

### ISSUE THREAD

**Issue by nodesocket** [amazonwebservices/aws-sdk-for-php#64]
I am trying to list all ec2 instances, and have the following:

``` php
<?php
    namespace Aws\Common\Aws;
    namespace Aws\Ec2;

    require_once(dirname(__DIR__) . "/lib/aws/aws-autoloader.php");

    $aws = Aws::factory(array(
        'key'    => getenv('amazon_key'),
        'secret' => getenv('amazon_secret')
    ));

    $ec2 = $aws->get("ec2");
    $instances = $ec2->DescribeInstances();

    print_r($instances);
?>

But I am getting:

```

<b>Fatal error</b>:  Class 'Aws\Ec2\CSRF' not found

```
```

**Comment by jeremeamia** [comment]
There are a few things wrong with this code, like using `namespace` instead of `use`. It should be `use Aws\Common\Aws;` You might consider giving the [namespaces section of the PHP manual](http://www.php.net/namespaces) a read if you are unfamiliar with namespaces.

Can you repost this on the [AWS SDK for PHP 2.x issue tracker](https://github.com/aws/aws-sdk-php/issues)? This issue tracker is for version 1.x.
